"""Static technology registry knowledge for the Detection Agent Tool.

Independent data set (display name, category, dependency package names)
carrying the project's existing detection knowledge. This module is data
only: matching logic lives in ``registry.py``. Keep matching deterministic
and case-insensitive via lowercased package keys at build time.

The order of entries is preserved from the source knowledge and is the
deterministic tie-break order used when several technologies share one
package name.
"""

from __future__ import annotations

# name, category, dependency packages
TECHNOLOGY_ENTRIES: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    ('Django', 'framework', ('django',)),
    ('Flask', 'framework', ('flask',)),
    ('FastAPI', 'framework', ('fastapi',)),
    ('Starlette', 'framework', ('starlette',)),
    ('Tornado', 'framework', ('tornado',)),
    ('Pyramid', 'framework', ('pyramid',)),
    ('Bottle', 'framework', ('bottle',)),
    ('Sanic', 'framework', ('sanic',)),
    ('aiohttp', 'framework', ('aiohttp',)),
    ('SQLAlchemy', 'orm', ('sqlalchemy',)),
    ('Peewee', 'orm', ('peewee',)),
    ('Tortoise ORM', 'orm', ('tortoise-orm',)),
    ('Jinja2', 'template_engine', ('jinja2',)),
    ('Mako', 'template_engine', ('mako',)),
    ('Pytest', 'testing', ('pytest',)),
    ('Celery', 'library', ('celery',)),
    ('Pydantic', 'library', ('pydantic',)),
    ('Litestar', 'framework', ('litestar',)),
    ('Falcon', 'framework', ('falcon',)),
    ('Django REST Framework', 'library', ('djangorestframework',)),
    ('Alembic', 'library', ('alembic',)),
    ('SQLModel', 'orm', ('sqlmodel',)),
    ('Requests', 'library', ('requests',)),
    ('httpx', 'library', ('httpx',)),
    ('NumPy', 'library', ('numpy',)),
    ('Pandas', 'library', ('pandas',)),
    ('PyTorch', 'library', ('torch',)),
    ('TensorFlow', 'library', ('tensorflow',)),
    ('scikit-learn', 'library', ('scikit-learn',)),
    ('LangChain', 'library', ('langchain',)),
    ('Transformers', 'library', ('transformers',)),
    ('Matplotlib', 'library', ('matplotlib',)),
    ('Pillow', 'library', ('pillow',)),
    ('OpenCV', 'library', ('opencv-python',)),
    ('Beautiful Soup', 'library', ('beautifulsoup4',)),
    ('Click', 'library', ('click',)),
    ('Typer', 'library', ('typer',)),
    ('Rich', 'library', ('rich',)),
    ('Loguru', 'library', ('loguru',)),
    ('Gunicorn', 'library', ('gunicorn',)),
    ('Uvicorn', 'library', ('uvicorn',)),
    ('Redis', 'library', ('redis',)),
    ('Psycopg', 'library', ('psycopg2', 'psycopg2-binary', 'psycopg',)),
    ('asyncpg', 'library', ('asyncpg',)),
    ('Motor', 'library', ('motor',)),
    ('Django Ninja', 'framework', ('django-ninja',)),
    ('Authlib', 'library', ('authlib',)),
    ('PyJWT', 'library', ('pyjwt',)),
    ('python-dotenv', 'library', ('python-dotenv',)),
    ('Boto3', 'library', ('boto3',)),
    ('OpenAI', 'library', ('openai',)),
    ('Scrapy', 'framework', ('scrapy',)),
    ('Selenium', 'testing', ('selenium',)),
    ('Playwright', 'testing', ('playwright',)),
    ('factory_boy', 'testing', ('factory-boy',)),
    ('Hypothesis', 'testing', ('hypothesis',)),
    ('pytest-cov', 'testing', ('pytest-cov',)),
    ('pytest-asyncio', 'testing', ('pytest-asyncio',)),
    ('pytest-django', 'testing', ('pytest-django',)),
    ('coverage.py', 'testing', ('coverage',)),
    ('tox', 'testing', ('tox',)),
    ('mypy', 'testing', ('mypy',)),
    ('ruff', 'library', ('ruff',)),
    ('Poetry', 'library', ('poetry',)),
    ('Apache Airflow', 'framework', ('apache-airflow',)),
    ('Dramatiq', 'library', ('dramatiq',)),
    ('APScheduler', 'library', ('apscheduler',)),
    ('spaCy', 'library', ('spacy',)),
    ('NLTK', 'library', ('nltk',)),
    ('PySpark', 'library', ('pyspark',)),
    ('WebSockets', 'library', ('websockets',)),
    ('React', 'framework', ('react',)),
    ('Next.js', 'framework', ('next',)),
    ('Vue', 'framework', ('vue',)),
    ('Nuxt', 'framework', ('nuxt',)),
    ('Angular', 'framework', ('@angular/core',)),
    ('Svelte', 'framework', ('svelte',)),
    ('SvelteKit', 'framework', ('@sveltejs/kit',)),
    ('Express', 'framework', ('express',)),
    ('Fastify', 'framework', ('fastify',)),
    ('NestJS', 'framework', ('@nestjs/core',)),
    ('Hono', 'framework', ('hono',)),
    ('Solid', 'framework', ('solid-js',)),
    ('Remix', 'framework', ('@remix-run/react',)),
    ('Astro', 'framework', ('astro',)),
    ('Koa', 'framework', ('koa',)),
    ('Prisma', 'orm', ('@prisma/client',)),
    ('TypeORM', 'orm', ('typeorm',)),
    ('Drizzle ORM', 'orm', ('drizzle-orm',)),
    ('Sequelize', 'orm', ('sequelize',)),
    ('Mongoose', 'orm', ('mongoose',)),
    ('Handlebars', 'template_engine', ('handlebars',)),
    ('EJS', 'template_engine', ('ejs',)),
    ('Pug', 'template_engine', ('pug',)),
    ('Jest', 'testing', ('jest',)),
    ('Vitest', 'testing', ('vitest',)),
    ('Mocha', 'testing', ('mocha',)),
    ('Cypress', 'testing', ('cypress',)),
    ('Playwright', 'testing', ('@playwright/test',)),
    ('Lodash', 'library', ('lodash',)),
    ('Axios', 'library', ('axios',)),
    ('Zod', 'library', ('zod',)),
    ('tRPC', 'library', ('@trpc/server',)),
    ('Redux', 'library', ('redux',)),
    ('Zustand', 'library', ('zustand',)),
    ('TanStack Query', 'library', ('@tanstack/react-query',)),
    ('Tailwind CSS', 'library', ('tailwindcss',)),
    ('React Native', 'framework', ('react-native',)),
    ('Electron', 'framework', ('electron',)),
    ('React Router', 'library', ('react-router-dom',)),
    ('React Hook Form', 'library', ('react-hook-form',)),
    ('SWR', 'library', ('swr',)),
    ('Material UI', 'library', ('@mui/material', '@mui/icons-material',)),
    ('Chakra UI', 'library', ('@chakra-ui/react',)),
    ('Ant Design', 'library', ('antd',)),
    ('Vite', 'library', ('vite',)),
    ('Webpack', 'library', ('webpack',)),
    ('TypeScript', 'library', ('typescript',)),
    ('date-fns', 'library', ('date-fns',)),
    ('Day.js', 'library', ('dayjs',)),
    ('Passport', 'library', ('passport',)),
    ('jsonwebtoken', 'library', ('jsonwebtoken',)),
    ('Socket.IO', 'library', ('socket.io', 'socket.io-client',)),
    ('GraphQL', 'library', ('graphql',)),
    ('Apollo', 'library', ('@apollo/client', 'apollo-server',)),
    ('ioredis', 'library', ('ioredis',)),
    ('Bull', 'library', ('bull',)),
    ('BullMQ', 'library', ('bullmq',)),
    ('Sass', 'library', ('sass',)),
    ('PostCSS', 'library', ('postcss',)),
    ('Bootstrap', 'library', ('bootstrap',)),
    ('Framer Motion', 'library', ('framer-motion',)),
    ('Three.js', 'library', ('three',)),
    ('D3.js', 'library', ('d3',)),
    ('Chart.js', 'library', ('chart.js',)),
    ('styled-components', 'library', ('styled-components',)),
    ('Emotion', 'library', ('@emotion/react',)),
    ('Knex', 'orm', ('knex',)),
    ('Yup', 'library', ('yup',)),
    ('Formik', 'library', ('formik',)),
    ('Laravel', 'framework', ('laravel/framework',)),
    ('Symfony', 'framework', ('symfony/framework-bundle',)),
    ('CodeIgniter', 'framework', ('codeigniter/framework',)),
    ('CakePHP', 'framework', ('cakephp/cakephp',)),
    ('Yii', 'framework', ('yiisoft/yii2',)),
    ('Phalcon', 'framework', ('phalcon/cphalcon',)),
    ('Slim', 'framework', ('slim/slim',)),
    ('Blade', 'template_engine', ('illuminate/view',)),
    ('Twig', 'template_engine', ('twig/twig',)),
    ('Eloquent', 'orm', ('illuminate/database',)),
    ('Doctrine', 'orm', ('doctrine/orm',)),
    ('PHPUnit', 'testing', ('phpunit/phpunit',)),
    ('Pest', 'testing', ('pestphp/pest',)),
    ('Guzzle', 'library', ('guzzlehttp/guzzle',)),
    ('Livewire', 'library', ('livewire/livewire',)),
    ('Monolog', 'library', ('monolog/monolog',)),
    ('Laminas', 'framework', ('laminas/laminas-mvc',)),
    ('Mezzio', 'framework', ('mezzio/mezzio',)),
    ('Symfony Console', 'library', ('symfony/console',)),
    ('PHPStan', 'testing', ('phpstan/phpstan',)),
    ('PHP CS Fixer', 'library', ('friendsofphp/php-cs-fixer',)),
    ('PHP_CodeSniffer', 'testing', ('squizlabs/php_codesniffer',)),
    ('Doctrine DBAL', 'orm', ('doctrine/dbal',)),
    ('Laravel Sanctum', 'library', ('laravel/sanctum',)),
    ('Laravel Horizon', 'library', ('laravel/horizon',)),
    ('Laravel Telescope', 'library', ('laravel/telescope',)),
    ('Laravel Socialite', 'library', ('laravel/socialite',)),
    ('Laravel Debugbar', 'library', ('barryvdh/laravel-debugbar',)),
    ('Laravel IDE Helper', 'library', ('barryvdh/laravel-ide-helper',)),
    ('Predis', 'library', ('predis/predis',)),
    ('php-amqplib', 'library', ('php-amqplib/php-amqplib',)),
    ('Carbon', 'library', ('nesbot/carbon',)),
    ('Spatie Permissions', 'library', ('spatie/laravel-permission',)),
    ('Spatie Media Library', 'library', ('spatie/laravel-medialibrary',)),
    ('Spring Boot', 'framework', ('spring-boot-starter', 'spring-boot',)),
    ('Spring Framework', 'framework', ('spring-core', 'spring-context',)),
    ('Jakarta EE', 'framework', ('jakarta.jakartaee',)),
    ('Micronaut', 'framework', ('io.micronaut',)),
    ('Quarkus', 'framework', ('io.quarkus',)),
    ('Grails', 'framework', ('grails', 'org.grails',)),
    ('Play Framework', 'framework', ('play', 'com.typesafe.play',)),
    ('Hibernate', 'orm', ('hibernate-core',)),
    ('MyBatis', 'orm', ('mybatis',)),
    ('Thymeleaf', 'template_engine', ('thymeleaf',)),
    ('JUnit', 'testing', ('junit', 'junit-jupiter',)),
    ('Mockito', 'testing', ('mockito-core',)),
    ('TestNG', 'testing', ('testng',)),
    ('Lombok', 'library', ('lombok',)),
    ('Vert.x', 'framework', ('io.vertx',)),
    ('Dropwizard', 'framework', ('dropwizard-core',)),
    ('Helidon', 'framework', ('io.helidon',)),
    ('Spring Data JPA', 'orm', ('spring-data-jpa',)),
    ('Spring Security', 'library', ('spring-security-config', 'spring-security-core',)),
    ('Spring Cloud', 'library', ('spring-cloud-starter',)),
    ('Jackson', 'library', ('jackson-databind', 'jackson-core',)),
    ('SLF4J', 'library', ('slf4j-api',)),
    ('Logback', 'library', ('logback-classic',)),
    ('Guava', 'library', ('guava',)),
    ('OkHttp', 'library', ('okhttp',)),
    ('Retrofit', 'library', ('retrofit',)),
    ('Netty', 'library', ('netty-all',)),
    ('JOOQ', 'orm', ('jooq',)),
    ('Flyway', 'library', ('flyway-core', 'flyway-maven-plugin',)),
    ('Liquibase', 'library', ('liquibase-core',)),
    ('MapStruct', 'library', ('mapstruct',)),
    ('Caffeine', 'library', ('caffeine',)),
    ('AssertJ', 'testing', ('assertj-core',)),
    ('REST Assured', 'testing', ('rest-assured',)),
    ('WireMock', 'testing', ('wiremock',)),
    ('Apache Kafka', 'library', ('kafka-clients',)),
    ('Hibernate Validator', 'library', ('hibernate-validator',)),
    ('Resilience4j', 'library', ('resilience4j',)),
    ('ASP.NET Core', 'framework', ('microsoft.aspnetcore',)),
    ('Blazor', 'framework', ('microsoft.aspnetcore.components',)),
    ('Entity Framework Core', 'orm', ('microsoft.entityframeworkcore',)),
    ('Dapper', 'orm', ('dapper',)),
    ('NHibernate', 'orm', ('nhibernate',)),
    ('xUnit', 'testing', ('xunit',)),
    ('NUnit', 'testing', ('nunit',)),
    ('Moq', 'testing', ('moq',)),
    ('Serilog', 'library', ('serilog',)),
    ('AutoMapper', 'library', ('automapper',)),
    ('FluentValidation', 'library', ('fluentvalidation',)),
    ('MediatR', 'library', ('mediatr',)),
    ('.NET MAUI', 'framework', ('microsoft.maui',)),
    ('SignalR', 'library', ('microsoft.aspnetcore.signalr',)),
    ('MassTransit', 'library', ('masstransit',)),
    ('Polly', 'library', ('polly',)),
    ('Newtonsoft.Json', 'library', ('newtonsoft.json',)),
    ('Refit', 'library', ('refit',)),
    ('RestSharp', 'library', ('restsharp',)),
    ('Swashbuckle', 'library', ('swashbuckle.aspnetcore',)),
    ('FluentAssertions', 'testing', ('fluentassertions',)),
    ('NSubstitute', 'testing', ('nsubstitute',)),
    ('BenchmarkDotNet', 'testing', ('benchmarkdotnet',)),
    ('SpecFlow', 'testing', ('specflow',)),
    ('MongoDB Driver', 'library', ('mongodb.driver',)),
    ('StackExchange.Redis', 'library', ('stackexchange.redis',)),
    ('Hangfire', 'library', ('hangfire',)),
    ('Gin', 'framework', ('github.com/gin-gonic/gin',)),
    ('Echo', 'framework', ('github.com/labstack/echo',)),
    ('Fiber', 'framework', ('github.com/gofiber/fiber',)),
    ('Chi', 'framework', ('github.com/go-chi/chi',)),
    ('Gorilla Mux', 'framework', ('github.com/gorilla/mux',)),
    ('Buffalo', 'framework', ('github.com/gobuffalo/buffalo',)),
    ('Beego', 'framework', ('github.com/beego/beego',)),
    ('GORM', 'orm', ('gorm.io/gorm',)),
    ('Ent', 'orm', ('entgo.io/ent',)),
    ('Testify', 'testing', ('github.com/stretchr/testify',)),
    ('Cobra', 'library', ('github.com/spf13/cobra',)),
    ('Viper', 'library', ('github.com/spf13/viper',)),
    ('Zap', 'library', ('go.uber.org/zap',)),
    ('Logrus', 'library', ('github.com/sirupsen/logrus',)),
    ('HttpRouter', 'framework', ('github.com/julienschmidt/httprouter',)),
    ('Negroni', 'library', ('github.com/urfave/negroni',)),
    ('Gorilla WebSocket', 'library', ('github.com/gorilla/websocket',)),
    ('Go-Redis', 'library', ('github.com/go-redis/redis', 'github.com/redis/go-redis',)),
    ('MongoDB Go Driver', 'library', ('go.mongodb.org/mongo-driver',)),
    ('pgx', 'library', ('github.com/jackc/pgx',)),
    ('sqlx', 'library', ('github.com/jmoiron/sqlx',)),
    ('Go Kit', 'library', ('github.com/go-kit/kit',)),
    ('Wire', 'library', ('github.com/google/wire',)),
    ('Fx', 'library', ('go.uber.org/fx',)),
    ('Prometheus', 'library', ('github.com/prometheus/client_golang',)),
    ('OpenTelemetry', 'library', ('go.opentelemetry.io/otel',)),
    ('gRPC-Go', 'library', ('google.golang.org/grpc',)),
    ('Casbin', 'library', ('github.com/casbin/casbin',)),
    ('golang-jwt', 'library', ('github.com/golang-jwt/jwt',)),
    ('go-playground/validator', 'library', ('github.com/go-playground/validator',)),
    ('golang-migrate', 'library', ('github.com/golang-migrate/migrate',)),
    ('Gorilla Sessions', 'library', ('github.com/gorilla/sessions',)),
    ('Actix-web', 'framework', ('actix-web',)),
    ('Axum', 'framework', ('axum',)),
    ('Rocket', 'framework', ('rocket',)),
    ('Warp', 'framework', ('warp',)),
    ('Tide', 'framework', ('tide',)),
    ('Poem', 'framework', ('poem',)),
    ('Diesel', 'orm', ('diesel',)),
    ('SeaORM', 'orm', ('sea-orm',)),
    ('Tokio', 'library', ('tokio',)),
    ('Serde', 'library', ('serde',)),
    ('Reqwest', 'library', ('reqwest',)),
    ('Tracing', 'library', ('tracing',)),
    ('Clap', 'library', ('clap',)),
    ('Leptos', 'framework', ('leptos',)),
    ('Yew', 'framework', ('yew',)),
    ('Dioxus', 'framework', ('dioxus',)),
    ('sqlx', 'orm', ('sqlx',)),
    ('Hyper', 'library', ('hyper',)),
    ('Tonic', 'library', ('tonic',)),
    ('anyhow', 'library', ('anyhow',)),
    ('thiserror', 'library', ('thiserror',)),
    ('chrono', 'library', ('chrono',)),
    ('rand', 'library', ('rand',)),
    ('futures', 'library', ('futures',)),
    ('async-trait', 'library', ('async-trait',)),
    ('tower', 'library', ('tower',)),
    ('Tower HTTP', 'library', ('tower-http',)),
    ('Lambda Runtime', 'library', ('lambda-runtime',)),
    ('Bevy', 'framework', ('bevy',)),
    ('Rusqlite', 'library', ('rusqlite',)),
    ('redis-rs', 'library', ('redis',)),
    ('Ruby on Rails', 'framework', ('rails',)),
    ('Sinatra', 'framework', ('sinatra',)),
    ('Hanami', 'framework', ('hanami',)),
    ('Active Record', 'orm', ('activerecord',)),
    ('Sequel', 'orm', ('sequel',)),
    ('RSpec', 'testing', ('rspec-rails', 'rspec',)),
    ('Minitest', 'testing', ('minitest',)),
    ('Capybara', 'testing', ('capybara',)),
    ('Factory Bot', 'testing', ('factory_bot',)),
    ('Devise', 'library', ('devise',)),
    ('Sidekiq', 'library', ('sidekiq',)),
    ('Kaminari', 'library', ('kaminari',)),
    ('Grape', 'framework', ('grape',)),
    ('Roda', 'framework', ('roda',)),
    ('Padrino', 'framework', ('padrino',)),
    ('Mongoid', 'orm', ('mongoid',)),
    ('ROM', 'orm', ('rom',)),
    ('Puma', 'library', ('puma',)),
    ('Pundit', 'library', ('pundit',)),
    ('CanCanCan', 'library', ('cancancan',)),
    ('Active Admin', 'library', ('activeadmin',)),
    ('Rails Admin', 'library', ('rails_admin',)),
    ('CarrierWave', 'library', ('carrierwave',)),
    ('Paperclip', 'library', ('paperclip',)),
    ('OmniAuth', 'library', ('omniauth',)),
    ('Doorkeeper', 'library', ('doorkeeper',)),
    ('Ransack', 'library', ('ransack',)),
    ('Searchkick', 'library', ('searchkick',)),
    ('Stripe', 'library', ('stripe',)),
    ('Resque', 'library', ('resque',)),
    ('Delayed Job', 'library', ('delayed_job',)),
    ('Good Job', 'library', ('good_job',)),
    ('Redis Ruby', 'library', ('redis',)),
    ('Sentry Ruby', 'library', ('sentry-ruby',)),
    ('AASM', 'library', ('aasm',)),
    ('Pagy', 'library', ('pagy',)),
    ('Rake', 'library', ('rake',)),
    ('SwiftUI', 'framework', ()),
    ('Vapor', 'framework', ('vapor',)),
    ('Kitura', 'framework', ('kitura',)),
    ('Alamofire', 'library', ('alamofire',)),
    ('SnapKit', 'library', ('snapkit',)),
    ('Kingfisher', 'library', ('kingfisher',)),
    ('RxSwift', 'library', ('rxswift',)),
    ('CoreData', 'orm', ()),
    ('SwiftData', 'orm', ()),
    ('XCTest', 'testing', ()),
    ('Quick', 'testing', ('quick',)),
    ('Nimble', 'testing', ('nimble',)),
    ('Combine', 'library', ()),
    ('GRDB', 'orm', ('grdb',)),
    ('SwiftHTTP', 'library', ()),
    ('Moya', 'library', ('moya',)),
    ('SwiftyJSON', 'library', ('swiftyjson',)),
    ('PromiseKit', 'library', ('promisekit',)),
    ('SwiftLint', 'library', ('swiftlint',)),
    ('Flutter', 'framework', ('flutter',)),
    ('Riverpod', 'library', ('riverpod',)),
    ('Provider', 'library', ('provider',)),
    ('Bloc', 'library', ('bloc',)),
    ('GetX', 'library', ('get',)),
    ('Dio', 'library', ('dio',)),
    ('Hive', 'library', ('hive',)),
    ('Shared Preferences', 'library', ('shared_preferences',)),
    ('Drift', 'orm', ('drift',)),
    ('Isar', 'orm', ('isar',)),
    ('Freezed', 'library', ('freezed',)),
    ('JSON Serializable', 'library', ('json_serializable',)),
    ('Cached Network Image', 'library', ('cached_network_image',)),
    ('Firebase', 'library', ('firebase_core',)),
    ('Flutter Secure Storage', 'library', ('flutter_secure_storage',)),
    ('Go Router', 'library', ('go_router',)),
    ('Flutter Bloc', 'library', ('flutter_bloc',)),
    ('Equatable', 'library', ('equatable',)),
    ('Intl', 'library', ('intl',)),
    ('URL Launcher', 'library', ('url_launcher',)),
    ('Image Picker', 'library', ('image_picker',)),
    ('Google Fonts', 'library', ('google_fonts',)),
    ('Ktor', 'framework', ('io.ktor',)),
    ('Kotlin Multiplatform', 'framework', ('org.jetbrains.kotlin.multiplatform',)),
    ('Jetpack Compose', 'library', ('androidx.compose.ui',)),
    ('Kotlin Coroutines', 'library', ('org.jetbrains.kotlinx:kotlinx-coroutines-core',)),
    ('Kotlinx Serialization', 'library', ('org.jetbrains.kotlinx:kotlinx-serialization-json',)),
    ('Exposed', 'orm', ('org.jetbrains.exposed', 'exposed-core',)),
    ('Koin', 'library', ('org.koin',)),
    ('Ktor Client', 'library', ('io.ktor:ktor-client',)),
    ('Kotlin Test', 'testing', ('org.jetbrains.kotlin:kotlin-test',)),
    ('MockK', 'testing', ('io.mockk',)),
    ('Kotlinx DateTime', 'library', ('org.jetbrains.kotlinx:kotlinx-datetime',)),
    ('Anko', 'library', ('org.jetbrains.anko',)),
    ('Akka', 'library', ('com.typesafe.akka',)),
    ('Apache Spark', 'library', ('org.apache.spark',)),
    ('ZIO', 'library', ('dev.zio',)),
    ('Cats', 'library', ('org.typelevel:cats-core',)),
    ('Cats Effect', 'library', ('org.typelevel:cats-effect',)),
    ('http4s', 'framework', ('org.http4s',)),
    ('Slick', 'orm', ('com.typesafe.slick',)),
    ('Doobie', 'orm', ('org.tpolecat:doobie-core',)),
    ('ScalaTest', 'testing', ('org.scalatest',)),
    ('ScalaCheck', 'testing', ('org.scalacheck',)),
    ('Specs2', 'testing', ('org.specs2',)),
    ('ScalaPB', 'library', ('scalapb',)),
    ('Circe', 'library', ('io.circe',)),
    ('Tapir', 'library', ('com.softwaremill.sttp.tapir',)),
    ('Sttp', 'library', ('com.softwaremill.sttp.client',)),
    ('Quill', 'orm', ('io.getquill',)),
    ('Gradle', 'library', ()),
    ('Geb', 'testing', ('org.gebish:geb-core',)),
    ('Spock', 'testing', ('org.spockframework:spock-core',)),
    ('Groovy Templates', 'template_engine', ('org.apache.groovy:groovy-templates',)),
    ('GPars', 'library', ('org.codehaus.gpars:gpars',)),
    ('Phoenix', 'framework', ('phoenix',)),
    ('Ecto', 'orm', ('ecto',)),
    ('Phoenix LiveView', 'framework', ('phoenix_live_view',)),
    ('Absinthe', 'library', ('absinthe',)),
    ('ExUnit', 'testing', ('ex_unit',)),
    ('Tesla', 'library', ('tesla',)),
    ('Poison', 'library', ('poison',)),
    ('Jason', 'library', ('jason',)),
    ('Broadway', 'library', ('broadway',)),
    ('Oban', 'library', ('oban',)),
    ('Mox', 'testing', ('mox',)),
    ('Nx', 'library', ('nx',)),
    ('Ash Framework', 'framework', ('ash',)),
)
