from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

FrameworkCategory = Literal[
    "framework",
    "orm",
    "template_engine",
    "testing",
    "library",
]


@dataclass
class FrameworkEntry:
    name: str
    category: FrameworkCategory
    dependency_packages: list[str] = field(default_factory=list)


_entries: list[FrameworkEntry] = []
_pkg_index: dict[str, list[FrameworkEntry]] = {}
_index_built: bool = False


def register(entry: FrameworkEntry) -> None:
    _entries.append(entry)


def all_entries() -> list[FrameworkEntry]:
    return list(_entries)


def _rebuild_index() -> None:
    global _index_built
    _pkg_index.clear()
    for e in _entries:
        for pkg in e.dependency_packages:
            _pkg_index.setdefault(pkg, []).append(e)
    _index_built = True


def match_by_dependency_package(package_name: str) -> list[FrameworkEntry]:
    if not _index_built:
        _rebuild_index()
    results: list[FrameworkEntry] = []
    seen: set[str] = set()
    pkg_lower = package_name.lower()
    for prefix, entries in _pkg_index.items():
        if pkg_lower == prefix or pkg_lower.startswith(prefix + ".") or pkg_lower.startswith(prefix + "/") or pkg_lower.startswith(prefix + ":"):
            for e in entries:
                if e.name not in seen:
                    seen.add(e.name)
                    results.append(e)
        else:
            for sep in (".", "/", ":"):
                if sep + prefix in pkg_lower:
                    for e in entries:
                        if e.name not in seen:
                            seen.add(e.name)
                            results.append(e)
                    break
    return results


# =========================================================================
# Framework data
# =========================================================================

# --- Python ---
register(FrameworkEntry(
    name="Django",
    category="framework",
    dependency_packages=["django"],
))
register(FrameworkEntry(
    name="Flask",
    category="framework",
    dependency_packages=["flask"],
))
register(FrameworkEntry(
    name="FastAPI",
    category="framework",
    dependency_packages=["fastapi"],
))
register(FrameworkEntry(
    name="Starlette",
    category="framework",
    dependency_packages=["starlette"],
))
register(FrameworkEntry(
    name="Tornado",
    category="framework",
    dependency_packages=["tornado"],
))
register(FrameworkEntry(
    name="Pyramid",
    category="framework",
    dependency_packages=["pyramid"],
))
register(FrameworkEntry(
    name="Bottle",
    category="framework",
    dependency_packages=["bottle"],
))
register(FrameworkEntry(
    name="Sanic",
    category="framework",
    dependency_packages=["sanic"],
))
register(FrameworkEntry(
    name="aiohttp",
    category="framework",
    dependency_packages=["aiohttp"],
))
register(FrameworkEntry(
    name="SQLAlchemy",
    category="orm",
    dependency_packages=["sqlalchemy"],
))
register(FrameworkEntry(
    name="Peewee",
    category="orm",
    dependency_packages=["peewee"],
))
register(FrameworkEntry(
    name="Tortoise ORM",
    category="orm",
    dependency_packages=["tortoise-orm"],
))
register(FrameworkEntry(
    name="Jinja2",
    category="template_engine",
    dependency_packages=["jinja2"],
))
register(FrameworkEntry(
    name="Mako",
    category="template_engine",
    dependency_packages=["mako"],
))
register(FrameworkEntry(
    name="Pytest",
    category="testing",
    dependency_packages=["pytest"],
))
register(FrameworkEntry(
    name="Celery",
    category="library",
    dependency_packages=["celery"],
))
register(FrameworkEntry(
    name="Pydantic",
    category="library",
    dependency_packages=["pydantic"],
))
register(FrameworkEntry(
    name="Litestar",
    category="framework",
    dependency_packages=["litestar"],
))
register(FrameworkEntry(
    name="Falcon",
    category="framework",
    dependency_packages=["falcon"],
))
register(FrameworkEntry(
    name="Django REST Framework",
    category="library",
    dependency_packages=["djangorestframework"],
))
register(FrameworkEntry(
    name="Alembic",
    category="library",
    dependency_packages=["alembic"],
))
register(FrameworkEntry(
    name="SQLModel",
    category="orm",
    dependency_packages=["sqlmodel"],
))
register(FrameworkEntry(
    name="Requests",
    category="library",
    dependency_packages=["requests"],
))
register(FrameworkEntry(
    name="httpx",
    category="library",
    dependency_packages=["httpx"],
))
register(FrameworkEntry(
    name="NumPy",
    category="library",
    dependency_packages=["numpy"],
))
register(FrameworkEntry(
    name="Pandas",
    category="library",
    dependency_packages=["pandas"],
))
register(FrameworkEntry(
    name="PyTorch",
    category="library",
    dependency_packages=["torch"],
))
register(FrameworkEntry(
    name="TensorFlow",
    category="library",
    dependency_packages=["tensorflow"],
))
register(FrameworkEntry(
    name="scikit-learn",
    category="library",
    dependency_packages=["scikit-learn"],
))
register(FrameworkEntry(
    name="LangChain",
    category="library",
    dependency_packages=["langchain"],
))
register(FrameworkEntry(
    name="Transformers",
    category="library",
    dependency_packages=["transformers"],
))
register(FrameworkEntry(
    name="Matplotlib",
    category="library",
    dependency_packages=["matplotlib"],
))
register(FrameworkEntry(
    name="Pillow",
    category="library",
    dependency_packages=["pillow"],
))
register(FrameworkEntry(
    name="OpenCV",
    category="library",
    dependency_packages=["opencv-python"],
))
register(FrameworkEntry(
    name="Beautiful Soup",
    category="library",
    dependency_packages=["beautifulsoup4"],
))
register(FrameworkEntry(
    name="Click",
    category="library",
    dependency_packages=["click"],
))
register(FrameworkEntry(
    name="Typer",
    category="library",
    dependency_packages=["typer"],
))
register(FrameworkEntry(
    name="Rich",
    category="library",
    dependency_packages=["rich"],
))
register(FrameworkEntry(
    name="Loguru",
    category="library",
    dependency_packages=["loguru"],
))
register(FrameworkEntry(
    name="Gunicorn",
    category="library",
    dependency_packages=["gunicorn"],
))
register(FrameworkEntry(
    name="Uvicorn",
    category="library",
    dependency_packages=["uvicorn"],
))
register(FrameworkEntry(
    name="Redis",
    category="library",
    dependency_packages=["redis"],
))
register(FrameworkEntry(
    name="Psycopg",
    category="library",
    dependency_packages=["psycopg2", "psycopg2-binary", "psycopg"],
))
register(FrameworkEntry(
    name="asyncpg",
    category="library",
    dependency_packages=["asyncpg"],
))
register(FrameworkEntry(
    name="Motor",
    category="library",
    dependency_packages=["motor"],
))
register(FrameworkEntry(
    name="Django Ninja",
    category="framework",
    dependency_packages=["django-ninja"],
))
register(FrameworkEntry(
    name="Authlib",
    category="library",
    dependency_packages=["authlib"],
))
register(FrameworkEntry(
    name="PyJWT",
    category="library",
    dependency_packages=["pyjwt"],
))
register(FrameworkEntry(
    name="python-dotenv",
    category="library",
    dependency_packages=["python-dotenv"],
))
register(FrameworkEntry(
    name="Boto3",
    category="library",
    dependency_packages=["boto3"],
))
register(FrameworkEntry(
    name="OpenAI",
    category="library",
    dependency_packages=["openai"],
))
register(FrameworkEntry(
    name="Scrapy",
    category="framework",
    dependency_packages=["scrapy"],
))
register(FrameworkEntry(
    name="Selenium",
    category="testing",
    dependency_packages=["selenium"],
))
register(FrameworkEntry(
    name="Playwright",
    category="testing",
    dependency_packages=["playwright"],
))
register(FrameworkEntry(
    name="factory_boy",
    category="testing",
    dependency_packages=["factory-boy"],
))
register(FrameworkEntry(
    name="Hypothesis",
    category="testing",
    dependency_packages=["hypothesis"],
))
register(FrameworkEntry(
    name="pytest-cov",
    category="testing",
    dependency_packages=["pytest-cov"],
))
register(FrameworkEntry(
    name="pytest-asyncio",
    category="testing",
    dependency_packages=["pytest-asyncio"],
))
register(FrameworkEntry(
    name="pytest-django",
    category="testing",
    dependency_packages=["pytest-django"],
))
register(FrameworkEntry(
    name="coverage.py",
    category="testing",
    dependency_packages=["coverage"],
))
register(FrameworkEntry(
    name="tox",
    category="testing",
    dependency_packages=["tox"],
))
register(FrameworkEntry(
    name="mypy",
    category="testing",
    dependency_packages=["mypy"],
))
register(FrameworkEntry(
    name="ruff",
    category="library",
    dependency_packages=["ruff"],
))
register(FrameworkEntry(
    name="Poetry",
    category="library",
    dependency_packages=["poetry"],
))
register(FrameworkEntry(
    name="Apache Airflow",
    category="framework",
    dependency_packages=["apache-airflow"],
))
register(FrameworkEntry(
    name="Dramatiq",
    category="library",
    dependency_packages=["dramatiq"],
))
register(FrameworkEntry(
    name="APScheduler",
    category="library",
    dependency_packages=["apscheduler"],
))
register(FrameworkEntry(
    name="spaCy",
    category="library",
    dependency_packages=["spacy"],
))
register(FrameworkEntry(
    name="NLTK",
    category="library",
    dependency_packages=["nltk"],
))
register(FrameworkEntry(
    name="PySpark",
    category="library",
    dependency_packages=["pyspark"],
))
register(FrameworkEntry(
    name="WebSockets",
    category="library",
    dependency_packages=["websockets"],
))

# --- JavaScript / TypeScript ---
register(FrameworkEntry(
    name="React",
    category="framework",
    dependency_packages=["react"],
))
register(FrameworkEntry(
    name="Next.js",
    category="framework",
    dependency_packages=["next"],
))
register(FrameworkEntry(
    name="Vue",
    category="framework",
    dependency_packages=["vue"],
))
register(FrameworkEntry(
    name="Nuxt",
    category="framework",
    dependency_packages=["nuxt"],
))
register(FrameworkEntry(
    name="Angular",
    category="framework",
    dependency_packages=["@angular/core"],
))
register(FrameworkEntry(
    name="Svelte",
    category="framework",
    dependency_packages=["svelte"],
))
register(FrameworkEntry(
    name="SvelteKit",
    category="framework",
    dependency_packages=["@sveltejs/kit"],
))
register(FrameworkEntry(
    name="Express",
    category="framework",
    dependency_packages=["express"],
))
register(FrameworkEntry(
    name="Fastify",
    category="framework",
    dependency_packages=["fastify"],
))
register(FrameworkEntry(
    name="NestJS",
    category="framework",
    dependency_packages=["@nestjs/core"],
))
register(FrameworkEntry(
    name="Hono",
    category="framework",
    dependency_packages=["hono"],
))
register(FrameworkEntry(
    name="Solid",
    category="framework",
    dependency_packages=["solid-js"],
))
register(FrameworkEntry(
    name="Remix",
    category="framework",
    dependency_packages=["@remix-run/react"],
))
register(FrameworkEntry(
    name="Astro",
    category="framework",
    dependency_packages=["astro"],
))
register(FrameworkEntry(
    name="Koa",
    category="framework",
    dependency_packages=["koa"],
))
register(FrameworkEntry(
    name="Prisma",
    category="orm",
    dependency_packages=["@prisma/client"],
))
register(FrameworkEntry(
    name="TypeORM",
    category="orm",
    dependency_packages=["typeorm"],
))
register(FrameworkEntry(
    name="Drizzle ORM",
    category="orm",
    dependency_packages=["drizzle-orm"],
))
register(FrameworkEntry(
    name="Sequelize",
    category="orm",
    dependency_packages=["sequelize"],
))
register(FrameworkEntry(
    name="Mongoose",
    category="orm",
    dependency_packages=["mongoose"],
))
register(FrameworkEntry(
    name="Handlebars",
    category="template_engine",
    dependency_packages=["handlebars"],
))
register(FrameworkEntry(
    name="EJS",
    category="template_engine",
    dependency_packages=["ejs"],
))
register(FrameworkEntry(
    name="Pug",
    category="template_engine",
    dependency_packages=["pug"],
))
register(FrameworkEntry(
    name="Jest",
    category="testing",
    dependency_packages=["jest"],
))
register(FrameworkEntry(
    name="Vitest",
    category="testing",
    dependency_packages=["vitest"],
))
register(FrameworkEntry(
    name="Mocha",
    category="testing",
    dependency_packages=["mocha"],
))
register(FrameworkEntry(
    name="Cypress",
    category="testing",
    dependency_packages=["cypress"],
))
register(FrameworkEntry(
    name="Playwright",
    category="testing",
    dependency_packages=["@playwright/test"],
))
register(FrameworkEntry(
    name="Lodash",
    category="library",
    dependency_packages=["lodash"],
))
register(FrameworkEntry(
    name="Axios",
    category="library",
    dependency_packages=["axios"],
))
register(FrameworkEntry(
    name="Zod",
    category="library",
    dependency_packages=["zod"],
))
register(FrameworkEntry(
    name="tRPC",
    category="library",
    dependency_packages=["@trpc/server"],
))
register(FrameworkEntry(
    name="Redux",
    category="library",
    dependency_packages=["redux"],
))
register(FrameworkEntry(
    name="Zustand",
    category="library",
    dependency_packages=["zustand"],
))
register(FrameworkEntry(
    name="TanStack Query",
    category="library",
    dependency_packages=["@tanstack/react-query"],
))
register(FrameworkEntry(
    name="Tailwind CSS",
    category="library",
    dependency_packages=["tailwindcss"],
))
register(FrameworkEntry(
    name="React Native",
    category="framework",
    dependency_packages=["react-native"],
))
register(FrameworkEntry(
    name="Electron",
    category="framework",
    dependency_packages=["electron"],
))
register(FrameworkEntry(
    name="React Router",
    category="library",
    dependency_packages=["react-router-dom"],
))
register(FrameworkEntry(
    name="React Hook Form",
    category="library",
    dependency_packages=["react-hook-form"],
))
register(FrameworkEntry(
    name="SWR",
    category="library",
    dependency_packages=["swr"],
))
register(FrameworkEntry(
    name="Material UI",
    category="library",
    dependency_packages=["@mui/material", "@mui/icons-material"],
))
register(FrameworkEntry(
    name="Chakra UI",
    category="library",
    dependency_packages=["@chakra-ui/react"],
))
register(FrameworkEntry(
    name="Ant Design",
    category="library",
    dependency_packages=["antd"],
))
register(FrameworkEntry(
    name="Vite",
    category="library",
    dependency_packages=["vite"],
))
register(FrameworkEntry(
    name="Webpack",
    category="library",
    dependency_packages=["webpack"],
))
register(FrameworkEntry(
    name="TypeScript",
    category="library",
    dependency_packages=["typescript"],
))
register(FrameworkEntry(
    name="date-fns",
    category="library",
    dependency_packages=["date-fns"],
))
register(FrameworkEntry(
    name="Day.js",
    category="library",
    dependency_packages=["dayjs"],
))
register(FrameworkEntry(
    name="Passport",
    category="library",
    dependency_packages=["passport"],
))
register(FrameworkEntry(
    name="jsonwebtoken",
    category="library",
    dependency_packages=["jsonwebtoken"],
))
register(FrameworkEntry(
    name="Socket.IO",
    category="library",
    dependency_packages=["socket.io", "socket.io-client"],
))
register(FrameworkEntry(
    name="GraphQL",
    category="library",
    dependency_packages=["graphql"],
))
register(FrameworkEntry(
    name="Apollo",
    category="library",
    dependency_packages=["@apollo/client", "apollo-server"],
))
register(FrameworkEntry(
    name="ioredis",
    category="library",
    dependency_packages=["ioredis"],
))
register(FrameworkEntry(
    name="Bull",
    category="library",
    dependency_packages=["bull"],
))
register(FrameworkEntry(
    name="BullMQ",
    category="library",
    dependency_packages=["bullmq"],
))
register(FrameworkEntry(
    name="Sass",
    category="library",
    dependency_packages=["sass"],
))
register(FrameworkEntry(
    name="PostCSS",
    category="library",
    dependency_packages=["postcss"],
))
register(FrameworkEntry(
    name="Bootstrap",
    category="library",
    dependency_packages=["bootstrap"],
))
register(FrameworkEntry(
    name="Framer Motion",
    category="library",
    dependency_packages=["framer-motion"],
))
register(FrameworkEntry(
    name="Three.js",
    category="library",
    dependency_packages=["three"],
))
register(FrameworkEntry(
    name="D3.js",
    category="library",
    dependency_packages=["d3"],
))
register(FrameworkEntry(
    name="Chart.js",
    category="library",
    dependency_packages=["chart.js"],
))
register(FrameworkEntry(
    name="styled-components",
    category="library",
    dependency_packages=["styled-components"],
))
register(FrameworkEntry(
    name="Emotion",
    category="library",
    dependency_packages=["@emotion/react"],
))
register(FrameworkEntry(
    name="Knex",
    category="orm",
    dependency_packages=["knex"],
))
register(FrameworkEntry(
    name="Yup",
    category="library",
    dependency_packages=["yup"],
))
register(FrameworkEntry(
    name="Formik",
    category="library",
    dependency_packages=["formik"],
))

# --- PHP ---
register(FrameworkEntry(
    name="Laravel",
    category="framework",
    dependency_packages=["laravel/framework"],
))
register(FrameworkEntry(
    name="Symfony",
    category="framework",
    dependency_packages=["symfony/framework-bundle"],
))
register(FrameworkEntry(
    name="CodeIgniter",
    category="framework",
    dependency_packages=["codeigniter/framework"],
))
register(FrameworkEntry(
    name="CakePHP",
    category="framework",
    dependency_packages=["cakephp/cakephp"],
))
register(FrameworkEntry(
    name="Yii",
    category="framework",
    dependency_packages=["yiisoft/yii2"],
))
register(FrameworkEntry(
    name="Phalcon",
    category="framework",
    dependency_packages=["phalcon/cphalcon"],
))
register(FrameworkEntry(
    name="Slim",
    category="framework",
    dependency_packages=["slim/slim"],
))
register(FrameworkEntry(
    name="Blade",
    category="template_engine",
    dependency_packages=["illuminate/view"],
))
register(FrameworkEntry(
    name="Twig",
    category="template_engine",
    dependency_packages=["twig/twig"],
))
register(FrameworkEntry(
    name="Eloquent",
    category="orm",
    dependency_packages=["illuminate/database"],
))
register(FrameworkEntry(
    name="Doctrine",
    category="orm",
    dependency_packages=["doctrine/orm"],
))
register(FrameworkEntry(
    name="PHPUnit",
    category="testing",
    dependency_packages=["phpunit/phpunit"],
))
register(FrameworkEntry(
    name="Pest",
    category="testing",
    dependency_packages=["pestphp/pest"],
))
register(FrameworkEntry(
    name="Guzzle",
    category="library",
    dependency_packages=["guzzlehttp/guzzle"],
))
register(FrameworkEntry(
    name="Livewire",
    category="library",
    dependency_packages=["livewire/livewire"],
))
register(FrameworkEntry(
    name="Monolog",
    category="library",
    dependency_packages=["monolog/monolog"],
))
register(FrameworkEntry(
    name="Laminas",
    category="framework",
    dependency_packages=["laminas/laminas-mvc"],
))
register(FrameworkEntry(
    name="Mezzio",
    category="framework",
    dependency_packages=["mezzio/mezzio"],
))
register(FrameworkEntry(
    name="Symfony Console",
    category="library",
    dependency_packages=["symfony/console"],
))
register(FrameworkEntry(
    name="PHPStan",
    category="testing",
    dependency_packages=["phpstan/phpstan"],
))
register(FrameworkEntry(
    name="PHP CS Fixer",
    category="library",
    dependency_packages=["friendsofphp/php-cs-fixer"],
))
register(FrameworkEntry(
    name="PHP_CodeSniffer",
    category="testing",
    dependency_packages=["squizlabs/php_codesniffer"],
))
register(FrameworkEntry(
    name="Doctrine DBAL",
    category="orm",
    dependency_packages=["doctrine/dbal"],
))
register(FrameworkEntry(
    name="Laravel Sanctum",
    category="library",
    dependency_packages=["laravel/sanctum"],
))
register(FrameworkEntry(
    name="Laravel Horizon",
    category="library",
    dependency_packages=["laravel/horizon"],
))
register(FrameworkEntry(
    name="Laravel Telescope",
    category="library",
    dependency_packages=["laravel/telescope"],
))
register(FrameworkEntry(
    name="Laravel Socialite",
    category="library",
    dependency_packages=["laravel/socialite"],
))
register(FrameworkEntry(
    name="Laravel Debugbar",
    category="library",
    dependency_packages=["barryvdh/laravel-debugbar"],
))
register(FrameworkEntry(
    name="Laravel IDE Helper",
    category="library",
    dependency_packages=["barryvdh/laravel-ide-helper"],
))
register(FrameworkEntry(
    name="Predis",
    category="library",
    dependency_packages=["predis/predis"],
))
register(FrameworkEntry(
    name="php-amqplib",
    category="library",
    dependency_packages=["php-amqplib/php-amqplib"],
))
register(FrameworkEntry(
    name="Carbon",
    category="library",
    dependency_packages=["nesbot/carbon"],
))
register(FrameworkEntry(
    name="Spatie Permissions",
    category="library",
    dependency_packages=["spatie/laravel-permission"],
))
register(FrameworkEntry(
    name="Spatie Media Library",
    category="library",
    dependency_packages=["spatie/laravel-medialibrary"],
))

# --- Java ---
register(FrameworkEntry(
    name="Spring Boot",
    category="framework",
    dependency_packages=["spring-boot-starter", "spring-boot"],
))
register(FrameworkEntry(
    name="Spring Framework",
    category="framework",
    dependency_packages=["spring-core", "spring-context"],
))
register(FrameworkEntry(
    name="Jakarta EE",
    category="framework",
    dependency_packages=["jakarta.jakartaee"],
))
register(FrameworkEntry(
    name="Micronaut",
    category="framework",
    dependency_packages=["io.micronaut"],
))
register(FrameworkEntry(
    name="Quarkus",
    category="framework",
    dependency_packages=["io.quarkus"],
))
register(FrameworkEntry(
    name="Grails",
    category="framework",
    dependency_packages=["grails", "org.grails"],
))
register(FrameworkEntry(
    name="Play Framework",
    category="framework",
    dependency_packages=["play", "com.typesafe.play"],
))
register(FrameworkEntry(
    name="Hibernate",
    category="orm",
    dependency_packages=["hibernate-core"],
))
register(FrameworkEntry(
    name="MyBatis",
    category="orm",
    dependency_packages=["mybatis"],
))
register(FrameworkEntry(
    name="Thymeleaf",
    category="template_engine",
    dependency_packages=["thymeleaf"],
))
register(FrameworkEntry(
    name="JUnit",
    category="testing",
    dependency_packages=["junit", "junit-jupiter"],
))
register(FrameworkEntry(
    name="Mockito",
    category="testing",
    dependency_packages=["mockito-core"],
))
register(FrameworkEntry(
    name="TestNG",
    category="testing",
    dependency_packages=["testng"],
))
register(FrameworkEntry(
    name="Lombok",
    category="library",
    dependency_packages=["lombok"],
))
register(FrameworkEntry(
    name="Vert.x",
    category="framework",
    dependency_packages=["io.vertx"],
))
register(FrameworkEntry(
    name="Dropwizard",
    category="framework",
    dependency_packages=["dropwizard-core"],
))
register(FrameworkEntry(
    name="Helidon",
    category="framework",
    dependency_packages=["io.helidon"],
))
register(FrameworkEntry(
    name="Spring Data JPA",
    category="orm",
    dependency_packages=["spring-data-jpa"],
))
register(FrameworkEntry(
    name="Spring Security",
    category="library",
    dependency_packages=["spring-security-config", "spring-security-core"],
))
register(FrameworkEntry(
    name="Spring Cloud",
    category="library",
    dependency_packages=["spring-cloud-starter"],
))
register(FrameworkEntry(
    name="Jackson",
    category="library",
    dependency_packages=["jackson-databind", "jackson-core"],
))
register(FrameworkEntry(
    name="SLF4J",
    category="library",
    dependency_packages=["slf4j-api"],
))
register(FrameworkEntry(
    name="Logback",
    category="library",
    dependency_packages=["logback-classic"],
))
register(FrameworkEntry(
    name="Guava",
    category="library",
    dependency_packages=["guava"],
))
register(FrameworkEntry(
    name="OkHttp",
    category="library",
    dependency_packages=["okhttp"],
))
register(FrameworkEntry(
    name="Retrofit",
    category="library",
    dependency_packages=["retrofit"],
))
register(FrameworkEntry(
    name="Netty",
    category="library",
    dependency_packages=["netty-all"],
))
register(FrameworkEntry(
    name="JOOQ",
    category="orm",
    dependency_packages=["jooq"],
))
register(FrameworkEntry(
    name="Flyway",
    category="library",
    dependency_packages=["flyway-core", "flyway-maven-plugin"],
))
register(FrameworkEntry(
    name="Liquibase",
    category="library",
    dependency_packages=["liquibase-core"],
))
register(FrameworkEntry(
    name="MapStruct",
    category="library",
    dependency_packages=["mapstruct"],
))
register(FrameworkEntry(
    name="Caffeine",
    category="library",
    dependency_packages=["caffeine"],
))
register(FrameworkEntry(
    name="AssertJ",
    category="testing",
    dependency_packages=["assertj-core"],
))
register(FrameworkEntry(
    name="REST Assured",
    category="testing",
    dependency_packages=["rest-assured"],
))
register(FrameworkEntry(
    name="WireMock",
    category="testing",
    dependency_packages=["wiremock"],
))
register(FrameworkEntry(
    name="Apache Kafka",
    category="library",
    dependency_packages=["kafka-clients"],
))
register(FrameworkEntry(
    name="Hibernate Validator",
    category="library",
    dependency_packages=["hibernate-validator"],
))
register(FrameworkEntry(
    name="Resilience4j",
    category="library",
    dependency_packages=["resilience4j"],
))

# --- C# / .NET ---
register(FrameworkEntry(
    name="ASP.NET Core",
    category="framework",
    dependency_packages=["microsoft.aspnetcore"],
))
register(FrameworkEntry(
    name="Blazor",
    category="framework",
    dependency_packages=["microsoft.aspnetcore.components"],
))
register(FrameworkEntry(
    name="Entity Framework Core",
    category="orm",
    dependency_packages=["microsoft.entityframeworkcore"],
))
register(FrameworkEntry(
    name="Dapper",
    category="orm",
    dependency_packages=["dapper"],
))
register(FrameworkEntry(
    name="NHibernate",
    category="orm",
    dependency_packages=["nhibernate"],
))
register(FrameworkEntry(
    name="xUnit",
    category="testing",
    dependency_packages=["xunit"],
))
register(FrameworkEntry(
    name="NUnit",
    category="testing",
    dependency_packages=["nunit"],
))
register(FrameworkEntry(
    name="Moq",
    category="testing",
    dependency_packages=["moq"],
))
register(FrameworkEntry(
    name="Serilog",
    category="library",
    dependency_packages=["serilog"],
))
register(FrameworkEntry(
    name="AutoMapper",
    category="library",
    dependency_packages=["automapper"],
))
register(FrameworkEntry(
    name="FluentValidation",
    category="library",
    dependency_packages=["fluentvalidation"],
))
register(FrameworkEntry(
    name="MediatR",
    category="library",
    dependency_packages=["mediatr"],
))
register(FrameworkEntry(
    name=".NET MAUI",
    category="framework",
    dependency_packages=["microsoft.maui"],
))
register(FrameworkEntry(
    name="SignalR",
    category="library",
    dependency_packages=["microsoft.aspnetcore.signalr"],
))
register(FrameworkEntry(
    name="MassTransit",
    category="library",
    dependency_packages=["masstransit"],
))
register(FrameworkEntry(
    name="Polly",
    category="library",
    dependency_packages=["polly"],
))
register(FrameworkEntry(
    name="Newtonsoft.Json",
    category="library",
    dependency_packages=["newtonsoft.json"],
))
register(FrameworkEntry(
    name="Refit",
    category="library",
    dependency_packages=["refit"],
))
register(FrameworkEntry(
    name="RestSharp",
    category="library",
    dependency_packages=["restsharp"],
))
register(FrameworkEntry(
    name="Swashbuckle",
    category="library",
    dependency_packages=["swashbuckle.aspnetcore"],
))
register(FrameworkEntry(
    name="FluentAssertions",
    category="testing",
    dependency_packages=["fluentassertions"],
))
register(FrameworkEntry(
    name="NSubstitute",
    category="testing",
    dependency_packages=["nsubstitute"],
))
register(FrameworkEntry(
    name="BenchmarkDotNet",
    category="testing",
    dependency_packages=["benchmarkdotnet"],
))
register(FrameworkEntry(
    name="SpecFlow",
    category="testing",
    dependency_packages=["specflow"],
))
register(FrameworkEntry(
    name="MongoDB Driver",
    category="library",
    dependency_packages=["mongodb.driver"],
))
register(FrameworkEntry(
    name="StackExchange.Redis",
    category="library",
    dependency_packages=["stackexchange.redis"],
))
register(FrameworkEntry(
    name="Hangfire",
    category="library",
    dependency_packages=["hangfire"],
))

# --- Go ---
register(FrameworkEntry(
    name="Gin",
    category="framework",
    dependency_packages=["github.com/gin-gonic/gin"],
))
register(FrameworkEntry(
    name="Echo",
    category="framework",
    dependency_packages=["github.com/labstack/echo"],
))
register(FrameworkEntry(
    name="Fiber",
    category="framework",
    dependency_packages=["github.com/gofiber/fiber"],
))
register(FrameworkEntry(
    name="Chi",
    category="framework",
    dependency_packages=["github.com/go-chi/chi"],
))
register(FrameworkEntry(
    name="Gorilla Mux",
    category="framework",
    dependency_packages=["github.com/gorilla/mux"],
))
register(FrameworkEntry(
    name="Buffalo",
    category="framework",
    dependency_packages=["github.com/gobuffalo/buffalo"],
))
register(FrameworkEntry(
    name="Beego",
    category="framework",
    dependency_packages=["github.com/beego/beego"],
))
register(FrameworkEntry(
    name="GORM",
    category="orm",
    dependency_packages=["gorm.io/gorm"],
))
register(FrameworkEntry(
    name="Ent",
    category="orm",
    dependency_packages=["entgo.io/ent"],
))
register(FrameworkEntry(
    name="Testify",
    category="testing",
    dependency_packages=["github.com/stretchr/testify"],
))
register(FrameworkEntry(
    name="Cobra",
    category="library",
    dependency_packages=["github.com/spf13/cobra"],
))
register(FrameworkEntry(
    name="Viper",
    category="library",
    dependency_packages=["github.com/spf13/viper"],
))
register(FrameworkEntry(
    name="Zap",
    category="library",
    dependency_packages=["go.uber.org/zap"],
))
register(FrameworkEntry(
    name="Logrus",
    category="library",
    dependency_packages=["github.com/sirupsen/logrus"],
))
register(FrameworkEntry(
    name="HttpRouter",
    category="framework",
    dependency_packages=["github.com/julienschmidt/httprouter"],
))
register(FrameworkEntry(
    name="Negroni",
    category="library",
    dependency_packages=["github.com/urfave/negroni"],
))
register(FrameworkEntry(
    name="Gorilla WebSocket",
    category="library",
    dependency_packages=["github.com/gorilla/websocket"],
))
register(FrameworkEntry(
    name="Go-Redis",
    category="library",
    dependency_packages=["github.com/go-redis/redis", "github.com/redis/go-redis"],
))
register(FrameworkEntry(
    name="MongoDB Go Driver",
    category="library",
    dependency_packages=["go.mongodb.org/mongo-driver"],
))
register(FrameworkEntry(
    name="pgx",
    category="library",
    dependency_packages=["github.com/jackc/pgx"],
))
register(FrameworkEntry(
    name="sqlx",
    category="library",
    dependency_packages=["github.com/jmoiron/sqlx"],
))
register(FrameworkEntry(
    name="Go Kit",
    category="library",
    dependency_packages=["github.com/go-kit/kit"],
))
register(FrameworkEntry(
    name="Wire",
    category="library",
    dependency_packages=["github.com/google/wire"],
))
register(FrameworkEntry(
    name="Fx",
    category="library",
    dependency_packages=["go.uber.org/fx"],
))
register(FrameworkEntry(
    name="Prometheus",
    category="library",
    dependency_packages=["github.com/prometheus/client_golang"],
))
register(FrameworkEntry(
    name="OpenTelemetry",
    category="library",
    dependency_packages=["go.opentelemetry.io/otel"],
))
register(FrameworkEntry(
    name="gRPC-Go",
    category="library",
    dependency_packages=["google.golang.org/grpc"],
))
register(FrameworkEntry(
    name="Casbin",
    category="library",
    dependency_packages=["github.com/casbin/casbin"],
))
register(FrameworkEntry(
    name="golang-jwt",
    category="library",
    dependency_packages=["github.com/golang-jwt/jwt"],
))
register(FrameworkEntry(
    name="go-playground/validator",
    category="library",
    dependency_packages=["github.com/go-playground/validator"],
))
register(FrameworkEntry(
    name="golang-migrate",
    category="library",
    dependency_packages=["github.com/golang-migrate/migrate"],
))
register(FrameworkEntry(
    name="Gorilla Sessions",
    category="library",
    dependency_packages=["github.com/gorilla/sessions"],
))

# --- Rust ---
register(FrameworkEntry(
    name="Actix-web",
    category="framework",
    dependency_packages=["actix-web"],
))
register(FrameworkEntry(
    name="Axum",
    category="framework",
    dependency_packages=["axum"],
))
register(FrameworkEntry(
    name="Rocket",
    category="framework",
    dependency_packages=["rocket"],
))
register(FrameworkEntry(
    name="Warp",
    category="framework",
    dependency_packages=["warp"],
))
register(FrameworkEntry(
    name="Tide",
    category="framework",
    dependency_packages=["tide"],
))
register(FrameworkEntry(
    name="Poem",
    category="framework",
    dependency_packages=["poem"],
))
register(FrameworkEntry(
    name="Diesel",
    category="orm",
    dependency_packages=["diesel"],
))
register(FrameworkEntry(
    name="SeaORM",
    category="orm",
    dependency_packages=["sea-orm"],
))
register(FrameworkEntry(
    name="Tokio",
    category="library",
    dependency_packages=["tokio"],
))
register(FrameworkEntry(
    name="Serde",
    category="library",
    dependency_packages=["serde"],
))
register(FrameworkEntry(
    name="Reqwest",
    category="library",
    dependency_packages=["reqwest"],
))
register(FrameworkEntry(
    name="Tracing",
    category="library",
    dependency_packages=["tracing"],
))
register(FrameworkEntry(
    name="Clap",
    category="library",
    dependency_packages=["clap"],
))
register(FrameworkEntry(
    name="Leptos",
    category="framework",
    dependency_packages=["leptos"],
))
register(FrameworkEntry(
    name="Yew",
    category="framework",
    dependency_packages=["yew"],
))
register(FrameworkEntry(
    name="Dioxus",
    category="framework",
    dependency_packages=["dioxus"],
))
register(FrameworkEntry(
    name="sqlx",
    category="orm",
    dependency_packages=["sqlx"],
))
register(FrameworkEntry(
    name="Hyper",
    category="library",
    dependency_packages=["hyper"],
))
register(FrameworkEntry(
    name="Tonic",
    category="library",
    dependency_packages=["tonic"],
))
register(FrameworkEntry(
    name="anyhow",
    category="library",
    dependency_packages=["anyhow"],
))
register(FrameworkEntry(
    name="thiserror",
    category="library",
    dependency_packages=["thiserror"],
))
register(FrameworkEntry(
    name="chrono",
    category="library",
    dependency_packages=["chrono"],
))
register(FrameworkEntry(
    name="rand",
    category="library",
    dependency_packages=["rand"],
))
register(FrameworkEntry(
    name="futures",
    category="library",
    dependency_packages=["futures"],
))
register(FrameworkEntry(
    name="async-trait",
    category="library",
    dependency_packages=["async-trait"],
))
register(FrameworkEntry(
    name="tower",
    category="library",
    dependency_packages=["tower"],
))
register(FrameworkEntry(
    name="Tower HTTP",
    category="library",
    dependency_packages=["tower-http"],
))
register(FrameworkEntry(
    name="Lambda Runtime",
    category="library",
    dependency_packages=["lambda-runtime"],
))
register(FrameworkEntry(
    name="Bevy",
    category="framework",
    dependency_packages=["bevy"],
))
register(FrameworkEntry(
    name="Rusqlite",
    category="library",
    dependency_packages=["rusqlite"],
))
register(FrameworkEntry(
    name="redis-rs",
    category="library",
    dependency_packages=["redis"],
))

# --- Ruby ---
register(FrameworkEntry(
    name="Ruby on Rails",
    category="framework",
    dependency_packages=["rails"],
))
register(FrameworkEntry(
    name="Sinatra",
    category="framework",
    dependency_packages=["sinatra"],
))
register(FrameworkEntry(
    name="Hanami",
    category="framework",
    dependency_packages=["hanami"],
))
register(FrameworkEntry(
    name="Active Record",
    category="orm",
    dependency_packages=["activerecord"],
))
register(FrameworkEntry(
    name="Sequel",
    category="orm",
    dependency_packages=["sequel"],
))
register(FrameworkEntry(
    name="RSpec",
    category="testing",
    dependency_packages=["rspec-rails", "rspec"],
))
register(FrameworkEntry(
    name="Minitest",
    category="testing",
    dependency_packages=["minitest"],
))
register(FrameworkEntry(
    name="Capybara",
    category="testing",
    dependency_packages=["capybara"],
))
register(FrameworkEntry(
    name="Factory Bot",
    category="testing",
    dependency_packages=["factory_bot"],
))
register(FrameworkEntry(
    name="Devise",
    category="library",
    dependency_packages=["devise"],
))
register(FrameworkEntry(
    name="Sidekiq",
    category="library",
    dependency_packages=["sidekiq"],
))
register(FrameworkEntry(
    name="Kaminari",
    category="library",
    dependency_packages=["kaminari"],
))
register(FrameworkEntry(
    name="Grape",
    category="framework",
    dependency_packages=["grape"],
))
register(FrameworkEntry(
    name="Roda",
    category="framework",
    dependency_packages=["roda"],
))
register(FrameworkEntry(
    name="Padrino",
    category="framework",
    dependency_packages=["padrino"],
))
register(FrameworkEntry(
    name="Mongoid",
    category="orm",
    dependency_packages=["mongoid"],
))
register(FrameworkEntry(
    name="ROM",
    category="orm",
    dependency_packages=["rom"],
))
register(FrameworkEntry(
    name="Puma",
    category="library",
    dependency_packages=["puma"],
))
register(FrameworkEntry(
    name="Pundit",
    category="library",
    dependency_packages=["pundit"],
))
register(FrameworkEntry(
    name="CanCanCan",
    category="library",
    dependency_packages=["cancancan"],
))
register(FrameworkEntry(
    name="Active Admin",
    category="library",
    dependency_packages=["activeadmin"],
))
register(FrameworkEntry(
    name="Rails Admin",
    category="library",
    dependency_packages=["rails_admin"],
))
register(FrameworkEntry(
    name="CarrierWave",
    category="library",
    dependency_packages=["carrierwave"],
))
register(FrameworkEntry(
    name="Paperclip",
    category="library",
    dependency_packages=["paperclip"],
))
register(FrameworkEntry(
    name="OmniAuth",
    category="library",
    dependency_packages=["omniauth"],
))
register(FrameworkEntry(
    name="Doorkeeper",
    category="library",
    dependency_packages=["doorkeeper"],
))
register(FrameworkEntry(
    name="Ransack",
    category="library",
    dependency_packages=["ransack"],
))
register(FrameworkEntry(
    name="Searchkick",
    category="library",
    dependency_packages=["searchkick"],
))
register(FrameworkEntry(
    name="Stripe",
    category="library",
    dependency_packages=["stripe"],
))
register(FrameworkEntry(
    name="Resque",
    category="library",
    dependency_packages=["resque"],
))
register(FrameworkEntry(
    name="Delayed Job",
    category="library",
    dependency_packages=["delayed_job"],
))
register(FrameworkEntry(
    name="Good Job",
    category="library",
    dependency_packages=["good_job"],
))
register(FrameworkEntry(
    name="Redis Ruby",
    category="library",
    dependency_packages=["redis"],
))
register(FrameworkEntry(
    name="Sentry Ruby",
    category="library",
    dependency_packages=["sentry-ruby"],
))
register(FrameworkEntry(
    name="AASM",
    category="library",
    dependency_packages=["aasm"],
))
register(FrameworkEntry(
    name="Pagy",
    category="library",
    dependency_packages=["pagy"],
))
register(FrameworkEntry(
    name="Rake",
    category="library",
    dependency_packages=["rake"],
))

# --- Swift ---
register(FrameworkEntry(
    name="SwiftUI",
    category="framework",
    dependency_packages=[],
))
register(FrameworkEntry(
    name="Vapor",
    category="framework",
    dependency_packages=["vapor"],
))
register(FrameworkEntry(
    name="Kitura",
    category="framework",
    dependency_packages=["kitura"],
))
register(FrameworkEntry(
    name="Alamofire",
    category="library",
    dependency_packages=["alamofire"],
))
register(FrameworkEntry(
    name="SnapKit",
    category="library",
    dependency_packages=["snapkit"],
))
register(FrameworkEntry(
    name="Kingfisher",
    category="library",
    dependency_packages=["kingfisher"],
))
register(FrameworkEntry(
    name="RxSwift",
    category="library",
    dependency_packages=["rxswift"],
))
register(FrameworkEntry(
    name="CoreData",
    category="orm",
    dependency_packages=[],
))
register(FrameworkEntry(
    name="SwiftData",
    category="orm",
    dependency_packages=[],
))
register(FrameworkEntry(
    name="XCTest",
    category="testing",
    dependency_packages=[],
))
register(FrameworkEntry(
    name="Quick",
    category="testing",
    dependency_packages=["quick"],
))
register(FrameworkEntry(
    name="Nimble",
    category="testing",
    dependency_packages=["nimble"],
))
register(FrameworkEntry(
    name="Combine",
    category="library",
    dependency_packages=[],
))
register(FrameworkEntry(
    name="GRDB",
    category="orm",
    dependency_packages=["grdb"],
))
register(FrameworkEntry(
    name="SwiftHTTP",
    category="library",
    dependency_packages=[],
))
register(FrameworkEntry(
    name="Moya",
    category="library",
    dependency_packages=["moya"],
))
register(FrameworkEntry(
    name="SwiftyJSON",
    category="library",
    dependency_packages=["swiftyjson"],
))
register(FrameworkEntry(
    name="PromiseKit",
    category="library",
    dependency_packages=["promisekit"],
))
register(FrameworkEntry(
    name="SwiftLint",
    category="library",
    dependency_packages=["swiftlint"],
))

# --- Flutter / Dart ---
register(FrameworkEntry(
    name="Flutter",
    category="framework",
    dependency_packages=["flutter"],
))
register(FrameworkEntry(
    name="Riverpod",
    category="library",
    dependency_packages=["riverpod"],
))
register(FrameworkEntry(
    name="Provider",
    category="library",
    dependency_packages=["provider"],
))
register(FrameworkEntry(
    name="Bloc",
    category="library",
    dependency_packages=["bloc"],
))
register(FrameworkEntry(
    name="GetX",
    category="library",
    dependency_packages=["get"],
))
register(FrameworkEntry(
    name="Dio",
    category="library",
    dependency_packages=["dio"],
))
register(FrameworkEntry(
    name="Hive",
    category="library",
    dependency_packages=["hive"],
))
register(FrameworkEntry(
    name="Shared Preferences",
    category="library",
    dependency_packages=["shared_preferences"],
))
register(FrameworkEntry(
    name="Drift",
    category="orm",
    dependency_packages=["drift"],
))
register(FrameworkEntry(
    name="Isar",
    category="orm",
    dependency_packages=["isar"],
))
register(FrameworkEntry(
    name="Freezed",
    category="library",
    dependency_packages=["freezed"],
))
register(FrameworkEntry(
    name="JSON Serializable",
    category="library",
    dependency_packages=["json_serializable"],
))
register(FrameworkEntry(
    name="Cached Network Image",
    category="library",
    dependency_packages=["cached_network_image"],
))
register(FrameworkEntry(
    name="Firebase",
    category="library",
    dependency_packages=["firebase_core"],
))
register(FrameworkEntry(
    name="Flutter Secure Storage",
    category="library",
    dependency_packages=["flutter_secure_storage"],
))
register(FrameworkEntry(
    name="Go Router",
    category="library",
    dependency_packages=["go_router"],
))
register(FrameworkEntry(
    name="Flutter Bloc",
    category="library",
    dependency_packages=["flutter_bloc"],
))
register(FrameworkEntry(
    name="Equatable",
    category="library",
    dependency_packages=["equatable"],
))
register(FrameworkEntry(
    name="Intl",
    category="library",
    dependency_packages=["intl"],
))
register(FrameworkEntry(
    name="URL Launcher",
    category="library",
    dependency_packages=["url_launcher"],
))
register(FrameworkEntry(
    name="Image Picker",
    category="library",
    dependency_packages=["image_picker"],
))
register(FrameworkEntry(
    name="Google Fonts",
    category="library",
    dependency_packages=["google_fonts"],
))

# --- Kotlin ---
register(FrameworkEntry(
    name="Ktor",
    category="framework",
    dependency_packages=["io.ktor"],
))
register(FrameworkEntry(
    name="Kotlin Multiplatform",
    category="framework",
    dependency_packages=["org.jetbrains.kotlin.multiplatform"],
))
register(FrameworkEntry(
    name="Jetpack Compose",
    category="library",
    dependency_packages=["androidx.compose.ui"],
))
register(FrameworkEntry(
    name="Kotlin Coroutines",
    category="library",
    dependency_packages=["org.jetbrains.kotlinx:kotlinx-coroutines-core"],
))
register(FrameworkEntry(
    name="Kotlinx Serialization",
    category="library",
    dependency_packages=["org.jetbrains.kotlinx:kotlinx-serialization-json"],
))
register(FrameworkEntry(
    name="Exposed",
    category="orm",
    dependency_packages=["org.jetbrains.exposed", "exposed-core"],
))
register(FrameworkEntry(
    name="Koin",
    category="library",
    dependency_packages=["org.koin"],
))
register(FrameworkEntry(
    name="Ktor Client",
    category="library",
    dependency_packages=["io.ktor:ktor-client"],
))
register(FrameworkEntry(
    name="Kotlin Test",
    category="testing",
    dependency_packages=["org.jetbrains.kotlin:kotlin-test"],
))
register(FrameworkEntry(
    name="MockK",
    category="testing",
    dependency_packages=["io.mockk"],
))
register(FrameworkEntry(
    name="Kotlinx DateTime",
    category="library",
    dependency_packages=["org.jetbrains.kotlinx:kotlinx-datetime"],
))
register(FrameworkEntry(
    name="Anko",
    category="library",
    dependency_packages=["org.jetbrains.anko"],
))

# --- Scala ---
register(FrameworkEntry(
    name="Akka",
    category="library",
    dependency_packages=["com.typesafe.akka"],
))
register(FrameworkEntry(
    name="Apache Spark",
    category="library",
    dependency_packages=["org.apache.spark"],
))
register(FrameworkEntry(
    name="ZIO",
    category="library",
    dependency_packages=["dev.zio"],
))
register(FrameworkEntry(
    name="Cats",
    category="library",
    dependency_packages=["org.typelevel:cats-core"],
))
register(FrameworkEntry(
    name="Cats Effect",
    category="library",
    dependency_packages=["org.typelevel:cats-effect"],
))
register(FrameworkEntry(
    name="http4s",
    category="framework",
    dependency_packages=["org.http4s"],
))
register(FrameworkEntry(
    name="Slick",
    category="orm",
    dependency_packages=["com.typesafe.slick"],
))
register(FrameworkEntry(
    name="Doobie",
    category="orm",
    dependency_packages=["org.tpolecat:doobie-core"],
))
register(FrameworkEntry(
    name="ScalaTest",
    category="testing",
    dependency_packages=["org.scalatest"],
))
register(FrameworkEntry(
    name="ScalaCheck",
    category="testing",
    dependency_packages=["org.scalacheck"],
))
register(FrameworkEntry(
    name="Specs2",
    category="testing",
    dependency_packages=["org.specs2"],
))
register(FrameworkEntry(
    name="ScalaPB",
    category="library",
    dependency_packages=["scalapb"],
))
register(FrameworkEntry(
    name="Circe",
    category="library",
    dependency_packages=["io.circe"],
))
register(FrameworkEntry(
    name="Tapir",
    category="library",
    dependency_packages=["com.softwaremill.sttp.tapir"],
))
register(FrameworkEntry(
    name="Sttp",
    category="library",
    dependency_packages=["com.softwaremill.sttp.client"],
))
register(FrameworkEntry(
    name="Quill",
    category="orm",
    dependency_packages=["io.getquill"],
))

# --- Groovy ---
register(FrameworkEntry(
    name="Gradle",
    category="library",
    dependency_packages=[],
))
register(FrameworkEntry(
    name="Geb",
    category="testing",
    dependency_packages=["org.gebish:geb-core"],
))
register(FrameworkEntry(
    name="Spock",
    category="testing",
    dependency_packages=["org.spockframework:spock-core"],
))
register(FrameworkEntry(
    name="Groovy Templates",
    category="template_engine",
    dependency_packages=["org.apache.groovy:groovy-templates"],
))
register(FrameworkEntry(
    name="GPars",
    category="library",
    dependency_packages=["org.codehaus.gpars:gpars"],
))

# --- Elixir ---
register(FrameworkEntry(
    name="Phoenix",
    category="framework",
    dependency_packages=["phoenix"],
))
register(FrameworkEntry(
    name="Ecto",
    category="orm",
    dependency_packages=["ecto"],
))
register(FrameworkEntry(
    name="Phoenix LiveView",
    category="framework",
    dependency_packages=["phoenix_live_view"],
))
register(FrameworkEntry(
    name="Absinthe",
    category="library",
    dependency_packages=["absinthe"],
))
register(FrameworkEntry(
    name="ExUnit",
    category="testing",
    dependency_packages=["ex_unit"],
))
register(FrameworkEntry(
    name="Tesla",
    category="library",
    dependency_packages=["tesla"],
))
register(FrameworkEntry(
    name="Poison",
    category="library",
    dependency_packages=["poison"],
))
register(FrameworkEntry(
    name="Jason",
    category="library",
    dependency_packages=["jason"],
))
register(FrameworkEntry(
    name="Broadway",
    category="library",
    dependency_packages=["broadway"],
))
register(FrameworkEntry(
    name="Oban",
    category="library",
    dependency_packages=["oban"],
))
register(FrameworkEntry(
    name="Mox",
    category="testing",
    dependency_packages=["mox"],
))
register(FrameworkEntry(
    name="Nx",
    category="library",
    dependency_packages=["nx"],
))
register(FrameworkEntry(
    name="Ash Framework",
    category="framework",
    dependency_packages=["ash"],
))
